### PR TITLE
Use linker flag "-undefined dynamic_lookup" only if supported

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
Now the linker doesn't complain about unknown flag, I am looking at this issue:

```
$ ~/Software/cmake-3.5.2-Linux-x86_64/bin/cmake ../weak-linking-demo && make
-- The C compiler identification is GNU 5.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Link flag '-undefined dynamic_lookup' supported - no
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jcfr/Projects/weak-linking-demo-build
Scanning dependencies of target number
[ 16%] Building C object CMakeFiles/number.dir/number.c.o
[ 33%] Linking C shared library libnumber.so
[ 33%] Built target number
Scanning dependencies of target counter
[ 50%] Building C object CMakeFiles/counter.dir/counter.c.o
[ 66%] Linking C shared module counter.so
[ 66%] Built target counter
Scanning dependencies of target main
[ 83%] Building C object CMakeFiles/main.dir/main.c.o
[100%] Linking C executable main
CMakeFiles/main.dir/main.c.o: In function `main':
main.c:(.text+0x3c): undefined reference to `dlopen'
main.c:(.text+0x5b): undefined reference to `dlclose'
main.c:(.text+0x79): undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
CMakeFiles/main.dir/build.make:95: recipe for target 'main' failed
make[2]: *** [main] Error 1
CMakeFiles/Makefile2:781: recipe for target 'CMakeFiles/main.dir/all' failed
make[1]: *** [CMakeFiles/main.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by jcfr** [comment]
All cases are failing with the same error:

```
$ for i in d00 d01 d10 d11 s00 s01 s10 s11; do echo "--- $i ---"; cat _build/${i}/${i}_build_log.txt; done
--- d00 ---
[ 33%] Built target number
[ 66%] Built target counter
[ 83%] Linking C executable main
CMakeFiles/main.dir/main.c.o: In function `main':
main.c:(.text+0x3c): undefined reference to `dlopen'
main.c:(.text+0x5b): undefined reference to `dlclose'
main.c:(.text+0x79): undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
CMakeFiles/main.dir/build.make:95: recipe for target 'main' failed
make[2]: *** [main] Error 1
CMakeFiles/Makefile2:781: recipe for target 'CMakeFiles/main.dir/all' failed
make[1]: *** [CMakeFiles/main.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
--- d01 ---
[ 33%] Built target number
[ 66%] Built target counter
[ 83%] Linking C executable main
CMakeFiles/main.dir/main.c.o: In function `main':
main.c:(.text+0x3c): undefined reference to `dlopen'
main.c:(.text+0x5b): undefined reference to `dlclose'
main.c:(.text+0x79): undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
CMakeFiles/main.dir/build.make:95: recipe for target 'main' failed
make[2]: *** [main] Error 1
CMakeFiles/Makefile2:781: recipe for target 'CMakeFiles/main.dir/all' failed
make[1]: *** [CMakeFiles/main.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
--- d10 ---
[ 33%] Built target number
[ 66%] Built target counter
[ 83%] Linking C executable main
CMakeFiles/main.dir/main.c.o: In function `main':
main.c:(.text+0x3c): undefined reference to `dlopen'
main.c:(.text+0x5b): undefined reference to `dlclose'
main.c:(.text+0x79): undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
CMakeFiles/main.dir/build.make:95: recipe for target 'main' failed
make[2]: *** [main] Error 1
CMakeFiles/Makefile2:781: recipe for target 'CMakeFiles/main.dir/all' failed
make[1]: *** [CMakeFiles/main.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
--- d11 ---
[ 33%] Built target number
[ 66%] Built target counter
[ 83%] Linking C executable main
CMakeFiles/main.dir/main.c.o: In function `main':
main.c:(.text+0x3c): undefined reference to `dlopen'
main.c:(.text+0x5b): undefined reference to `dlclose'
main.c:(.text+0x79): undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
CMakeFiles/main.dir/build.make:95: recipe for target 'main' failed
make[2]: *** [main] Error 1
CMakeFiles/Makefile2:781: recipe for target 'CMakeFiles/main.dir/all' failed
make[1]: *** [CMakeFiles/main.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
--- s00 ---
[ 33%] Built target number
[ 66%] Built target counter
[ 83%] Linking C executable main
CMakeFiles/main.dir/main.c.o: In function `main':
main.c:(.text+0x3c): undefined reference to `dlopen'
main.c:(.text+0x5b): undefined reference to `dlclose'
main.c:(.text+0x79): undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
CMakeFiles/main.dir/build.make:95: recipe for target 'main' failed
make[2]: *** [main] Error 1
CMakeFiles/Makefile2:781: recipe for target 'CMakeFiles/main.dir/all' failed
make[1]: *** [CMakeFiles/main.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
--- s01 ---
[ 33%] Built target number
[ 66%] Built target counter
[ 83%] Linking C executable main
CMakeFiles/main.dir/main.c.o: In function `main':
main.c:(.text+0x3c): undefined reference to `dlopen'
main.c:(.text+0x5b): undefined reference to `dlclose'
main.c:(.text+0x79): undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
CMakeFiles/main.dir/build.make:95: recipe for target 'main' failed
make[2]: *** [main] Error 1
CMakeFiles/Makefile2:781: recipe for target 'CMakeFiles/main.dir/all' failed
make[1]: *** [CMakeFiles/main.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
--- s10 ---
[ 33%] Built target number
[ 66%] Built target counter
[ 83%] Linking C executable main
CMakeFiles/main.dir/main.c.o: In function `main':
main.c:(.text+0x3c): undefined reference to `dlopen'
main.c:(.text+0x5b): undefined reference to `dlclose'
main.c:(.text+0x79): undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
CMakeFiles/main.dir/build.make:95: recipe for target 'main' failed
make[2]: *** [main] Error 1
CMakeFiles/Makefile2:781: recipe for target 'CMakeFiles/main.dir/all' failed
make[1]: *** [CMakeFiles/main.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
--- s11 ---
[ 33%] Built target number
[ 66%] Built target counter
[ 83%] Linking C executable main
CMakeFiles/main.dir/main.c.o: In function `main':
main.c:(.text+0x3c): undefined reference to `dlopen'
main.c:(.text+0x5b): undefined reference to `dlclose'
main.c:(.text+0x79): undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
CMakeFiles/main.dir/build.make:95: recipe for target 'main' failed
make[2]: *** [main] Error 1
CMakeFiles/Makefile2:781: recipe for target 'CMakeFiles/main.dir/all' failed
make[1]: *** [CMakeFiles/main.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by jcfr** [comment]
Better now:

```
$ PATH=/home/jcfr/Software/cmake-3.5.2-Linux-x86_64/bin:$PATH ./enumerateBuilds.bash 
<LIB_TYPE><LINK_MOD><LINK_EXE>
LIB_TYPE: d -> SHARED, s-> STATIC
LINK_MOD: 1 -> weak, 0 -> strong
LINK_EXE: 1 -> weak, 0 -> strong

d00 [configure success]
d00 [build ... failure]
d01 [configure success]
d01 [build ... success]
d10 [configure success]
d10 [build ... failure]
d11 [configure success]
d11 [build ... success]
s00 [configure success]
s00 [build ... failure]
s01 [configure success]
s01 [build ... success]
s10 [configure success]
s10 [build ... failure]
s11 [configure success]
s11 [build ... success]
```

**Comment by jcfr** [comment]
And corresponding logs:

```
$ for i in d00 d01 d10 d11 s00 s01 s10 s11; do echo "--- $i ---"; cat _build/${i}/${i}_build_log.txt; done
--- d00 ---
[ 33%] Built target counter
[ 66%] Built target number
[ 83%] Linking C executable main
CMakeFiles/main.dir/main.c.o: In function `my_count':
main.c:(.text+0x9): undefined reference to `get_number'
main.c:(.text+0x19): undefined reference to `set_number'
collect2: error: ld returned 1 exit status
CMakeFiles/main.dir/build.make:94: recipe for target 'main' failed
make[2]: *** [main] Error 1
CMakeFiles/Makefile2:781: recipe for target 'CMakeFiles/main.dir/all' failed
make[1]: *** [CMakeFiles/main.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
--- d01 ---
[ 33%] Built target counter
[ 66%] Built target number
[ 83%] Linking C executable main
[100%] Built target main
--- d10 ---
[ 33%] Built target number
[ 66%] Built target counter
[ 83%] Linking C executable main
CMakeFiles/main.dir/main.c.o: In function `my_count':
main.c:(.text+0x9): undefined reference to `get_number'
main.c:(.text+0x19): undefined reference to `set_number'
collect2: error: ld returned 1 exit status
CMakeFiles/main.dir/build.make:94: recipe for target 'main' failed
make[2]: *** [main] Error 1
CMakeFiles/Makefile2:781: recipe for target 'CMakeFiles/main.dir/all' failed
make[1]: *** [CMakeFiles/main.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
--- d11 ---
[ 33%] Built target number
[ 66%] Built target counter
[ 83%] Linking C executable main
[100%] Built target main
--- s00 ---
[ 33%] Built target counter
[ 66%] Built target number
[ 83%] Linking C executable main
CMakeFiles/main.dir/main.c.o: In function `my_count':
main.c:(.text+0x9): undefined reference to `get_number'
main.c:(.text+0x19): undefined reference to `set_number'
collect2: error: ld returned 1 exit status
CMakeFiles/main.dir/build.make:94: recipe for target 'main' failed
make[2]: *** [main] Error 1
CMakeFiles/Makefile2:781: recipe for target 'CMakeFiles/main.dir/all' failed
make[1]: *** [CMakeFiles/main.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
--- s01 ---
[ 33%] Built target counter
[ 66%] Built target number
[ 83%] Linking C executable main
[100%] Built target main
--- s10 ---
[ 33%] Built target number
[ 66%] Built target counter
[ 83%] Linking C executable main
CMakeFiles/main.dir/main.c.o: In function `my_count':
main.c:(.text+0x9): undefined reference to `get_number'
main.c:(.text+0x19): undefined reference to `set_number'
collect2: error: ld returned 1 exit status
CMakeFiles/main.dir/build.make:94: recipe for target 'main' failed
make[2]: *** [main] Error 1
CMakeFiles/Makefile2:781: recipe for target 'CMakeFiles/main.dir/all' failed
make[1]: *** [CMakeFiles/main.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
--- s11 ---
[ 33%] Built target number
[ 66%] Built target counter
[ 83%] Linking C executable main
[100%] Built target main
```

**Comment by jcfr** [comment]
d10 -> should be passing

s10 -> should be passing
s11 -> pass, but expected to fail 

TODO: Improve output of `enumerateBuilds.bash` to check against expected outcome

**Comment by opadron** [comment]
@jcfr Quick note about the build abbreviations: the two digits are supposed to indicate if the library is _actually_ linked, so a `0` would correspond to weak linking.

**Comment by jcfr** [comment]
Makes sense. That is my understanding.

**Comment by opadron** [comment]
See my changes ([opadron/add-linux-gcc-support](https://github.com/opadron/weak-linking-demo/compare/add-linux-gcc-support)).

**Comment by opadron** [comment]
Hey, @jcfr, can you look at my suggestions ([opadron/add-linux-gcc-support](https://github.com/opadron/weak-linking-demo/compare/add-linux-gcc-support)), and get back to me?

I'd like to have all this merged in before sharing it with the other CMake folks.

**Comment by jcfr** [comment]
Thanks.

Doing a clean checkout, running `./enumerateBuild.bash` doesn't output anything ...

**Comment by opadron** [comment]
The instructions are also changed.  See the updated README.md.

**Comment by jcfr** [comment]
Look like there is an issue, based on the README, simply running `` return failure on Linux. It looks like nothing is built ... 

```
$ rm -rf _build
$ rm -rf log
$ ./testAllBuilds.bash
CASE  CONFIG BUILD  TEST
s00   fail   fail   fail
s01   fail   fail   fail
s10   fail   fail   fail
s11   fail   fail   fail
d00   fail   fail   fail
d01   fail   fail   fail
d10   fail   fail   fail
d11   fail   fail   fail
```

**Comment by jcfr** [comment]
```
$ bash -version
GNU bash, version 4.3.42(1)-release (x86_64-pc-linux-gnu)
```

**Comment by jcfr** [comment]
Since not output was provided .. I forgot to use latest CMake

**Comment by opadron** [comment]
I got the same thing and for me, I don't have CMake installed.

**Comment by opadron** [comment]
I installed cmake 3.5.2 on Arch Linux and achieved the expected output results.

**Comment by jcfr** [comment]
LGTM

**Comment by opadron** [comment]
Just to confirm: this PR has your original PR + my changes in opadron/add-linux-gcc-support + your additional changes?  And everything looks good now and is ready to merge, yes?

**Comment by jcfr** [comment]
Yes. Looks good to merge. :+1:

**Pull request merged**
